-- D1 Schema for TanStack Form Builder Registry
-- Users table (anonymous users identified by cookie + fingerprint fallback)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,              -- UUID stored in cookie
  fingerprint TEXT,                 -- IP + UA hash (fallback identification)
  created_at INTEGER NOT NULL       -- Unix timestamp in milliseconds
);

-- Registry items table (forms/tables generated by users)
CREATE TABLE IF NOT EXISTS registry_items (
  id TEXT PRIMARY KEY,              -- e.g., "FormName-uuid"
  user_id TEXT,                     -- Links to users.id (nullable for anonymous)
  name TEXT NOT NULL,               -- Form/table name
  type TEXT NOT NULL DEFAULT 'form', -- 'form' or 'table'
  data TEXT NOT NULL,               -- JSON blob of registry content
  created_at INTEGER NOT NULL,      -- Unix timestamp in milliseconds
  expires_at INTEGER NOT NULL,      -- TTL expiration timestamp
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Index for fetching user's items
CREATE INDEX IF NOT EXISTS idx_registry_user ON registry_items(user_id);

-- Index for cleanup of expired items
CREATE INDEX IF NOT EXISTS idx_registry_expires ON registry_items(expires_at);

-- Index for fingerprint lookup (fallback user identification)
CREATE INDEX IF NOT EXISTS idx_users_fingerprint ON users(fingerprint);
