import type { ColumnConfig } from "@/types/table-types";

export const DEFAULT_TABLE_DATA = [
	{
		id: "1",
		name: "Kathryn Campbell",
		availability: "online",
		avatar: "1.png",
		status: "active",
		flag: "🇺🇸",
		email: "kathryn@apple.com",
		company: "Apple",
		role: "CEO",
		joined: "2021-04-15",
		location: "San Francisco, USA",
		balance: 5143.03,
	},
	{
		id: "2",
		name: "Robert Smith",
		availability: "away",
		avatar: "2.png",
		status: "inactive",
		flag: "🇬🇧",
		email: "robert@openai.com",
		company: "OpenAI",
		role: "CTO",
		joined: "2020-07-20",
		location: "London, UK",
		balance: 4321.87,
	},
	{
		id: "3",
		name: "Sophia Johnson",
		availability: "busy",
		avatar: "3.png",
		status: "active",
		flag: "🇨🇦",
		email: "sophia@meta.com",
		company: "Meta",
		role: "Designer",
		joined: "2019-03-12",
		location: "Toronto, Canada",
		balance: 7654.98,
	},
	{
		id: "4",
		name: "Lucas Walker",
		availability: "offline",
		avatar: "4.png",
		status: "inactive",
		flag: "🇦🇺",
		email: "lucas@tesla.com",
		company: "Tesla",
		role: "Developer",
		joined: "2022-01-18",
		location: "Sydney, Australia",
		balance: 3456.45,
	},
	{
		id: "5",
		name: "Emily Davis",
		availability: "online",
		avatar: "5.png",
		status: "active",
		flag: "🇩🇪",
		email: "emily@sap.com",
		company: "SAP",
		role: "Lawyer",
		joined: "2023-05-23",
		location: "Berlin, Germany",
		balance: 9876.54,
	},
	{
		id: "6",
		name: "James Lee",
		availability: "away",
		avatar: "6.png",
		status: "active",
		flag: "🇲🇾",
		email: "james@keenthemes.com",
		company: "Keenthemes",
		role: "Director",
		joined: "2018-11-30",
		location: "Kuala Lumpur, MY",
		balance: 6214.22,
	},
	{
		id: "7",
		name: "Isabella Martinez",
		availability: "busy",
		avatar: "7.png",
		status: "inactive",
		flag: "🇪🇸",
		email: "isabella@bbva.es",
		company: "BBVA",
		role: "Product Manager",
		joined: "2021-06-14",
		location: "Barcelona, Spain",
		balance: 5321.77,
	},
	{
		id: "8",
		name: "Benjamin Harris",
		availability: "offline",
		avatar: "8.png",
		status: "active",
		flag: "🇯🇵",
		email: "benjamin@sony.jp",
		company: "Sony",
		role: "Marketing Lead",
		joined: "2020-10-22",
		location: "Tokyo, Japan",
		balance: 8452.39,
	},
	{
		id: "9",
		name: "Olivia Brown",
		availability: "online",
		avatar: "9.png",
		status: "active",
		flag: "🇫🇷",
		email: "olivia@lvmh.fr",
		company: "LVMH",
		role: "Data Scientist",
		joined: "2019-09-17",
		location: "Paris, France",
		balance: 7345.1,
	},
	{
		id: "10",
		name: "Michael Clark",
		availability: "away",
		avatar: "10.png",
		status: "inactive",
		flag: "🇮🇹",
		email: "michael@eni.it",
		company: "ENI",
		role: "Engineer",
		joined: "2023-02-11",
		location: "Milan, Italy",
		balance: 5214.88,
	},
	{
		id: "11",
		name: "Ava Wilson",
		availability: "busy",
		avatar: "11.png",
		status: "active",
		flag: "🇧🇷",
		email: "ava@vale.br",
		company: "Vale",
		role: "Software Engineer",
		joined: "2022-12-01",
		location: "Rio de Janeiro, Brazil",
		balance: 9421.5,
	},
	{
		id: "12",
		name: "David Young",
		availability: "offline",
		avatar: "12.png",
		status: "active",
		flag: "🇮🇳",
		email: "david@tata.in",
		company: "Tata",
		role: "Sales Manager",
		joined: "2020-03-27",
		location: "Mumbai, India",
		balance: 4521.67,
	},
];

export const DEFAULT_TABLE_COLUMNS: ColumnConfig[] = [
	{
		id: "id",
		accessor: "id",
		label: "ID",
		type: "number",
		order: 0,
		filterable: true,
	},
	{
		id: "name",
		accessor: "name",
		label: "Name",
		type: "string",
		order: 0,
		filterable: true,
	},
	{
		id: "email",
		accessor: "email",
		label: "Email",
		type: "email",
		order: 1,
		filterable: true,
	},
	{
		id: "status",
		accessor: "status",
		label: "Status",
		type: "enum",
		order: 2,
		filterable: true,
	},
	{
		id: "availability",
		accessor: "availability",
		label: "Availability",
		type: "enum",
		order: 3,
		filterable: true,
	},
	{
		id: "location",
		accessor: "location",
		label: "Location",
		type: "string",
		order: 4,
		filterable: true,
	},
	{
		id: "joined",
		accessor: "joined",
		label: "Joined",
		type: "date",
		order: 5,
		filterable: true,
	},
	{
		id: "balance",
		accessor: "balance",
		label: "Balance ($)",
		type: "number",
		order: 6,
		filterable: true,
	},
	{
		id: "avatar",
		accessor: "avatar",
		label: "Avatar",
		type: "string",
		order: 7,
		filterable: true,
	},
	{
		id: "flag",
		accessor: "flag",
		label: "Flag",
		type: "string",
		order: 8,
		filterable: true,
	},
	{
		id: "company",
		accessor: "company",
		label: "Company",
		type: "string",
		order: 9,
		filterable: true,
	},
	{
		id: "role",
		accessor: "role",
		label: "Role",
		type: "string",
		order: 10,
		filterable: true,
	},
];
